### ISSUE TITLE
Difficult to copy from console

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#80] opened 2019-03-30 08:23 UTC
You can't select and then click Ctrl+C since it unselects immediately. Not sure how to fix.

**Comment by rahularya50** [comment] 2019-03-30 08:24
This is also true for scheme.cs61a.org, right? Does it have the same cause?

**Comment by kavigupta** [comment] 2019-03-30 20:27
Yes it is true, I don't know the cause

**Comment by jathak** [comment] 2019-04-06 17:15
Not sure if the cause is the same, but the issue on scheme.cs61a.org was an overly aggressive listener that focused the current input field whenever the log was clicked. See Cal-CS-61A-Staff/dart_scheme#94.

**Comment by jathak** [comment] 2019-04-06 17:25
Figured out how to fix it here as well.

I can make a PR, but you need to add an open source license first so I can stay compliant with [my employer's policies](https://opensource.google.com/docs/patching/#patches-that-dont-require-any-review).

When adding a license, you should create an PR to add the license and have everyone who's committed so far approve it so you have a record that everyone agrees to release the code under that license (see [here](https://github.com/Cal-CS-61A-Staff/seating/pull/5) for an example of this).

**Comment by rahularya50** [comment] 2019-04-07 05:00
Fixed by #143

**Closed as completed by rahularya50** 2019-04-07 05:00 UTC
Labels: Priority: Low, Status: Completed
